### ISSUE TITLE
choosing "restart with the best mean rank of the SNV and SV predictive log likelihoods"

### ISSUE THREAD

**Issue by kerstinth** [shahcompbio/MultiModalMuSig.jl#12]
Hi,

Thanks for this cool tool!
I came across a few questions while running the MMCTM that I was hoping you could help me with:

I’ve read in the methods section of your paper: 
“Fitting MMCTM to cancer datasets for downstream analysis
The model was initially fit to each dataset 1000 times for a limited number of iterations. α
hyper-parameters were set to 0.1. Each restart is run until the relative difference in predictive
log likelihood on the training data was < 1e-4 between iterations. The restart with the best
mean rank of the SNV and SV predictive log likelihoods was selected for fitting to convergence with a tolerance of 1e-5.”

I’m not sure if I understand exactly what you mean by “best
mean rank of the SNV and SV predictive log likelihoods”. Does this mean I should fit the model with a tolerance of 1e-4 1000 times with random seeds for each restart and then choose the run which converges the fastest like this:

```
snv_counts = CSV.read("data/brca-eu_snv_counts.tsv", DataFrame, delim='\t')
sv_counts = CSV.read("data/brca-eu_sv_counts.tsv", DataFrame, delim='\t')

samples = [c for c in propertynames(snv_counts) if c != :term] 
X = format_counts_mmctm([snv_counts, sv_counts], samples)

seeds = rand(1:10000000, 1000)
log_length = zeros(1000)

for i in 1:1000 

	println(i)
	this_seed = seeds[i]

	Random.seed!(this_seed)

	model = MMCTM([6, 7], [0.1, 0.1], X)
	model_fit = fit!(model, tol=1e-4)

	log_length[i] = length(model_fit)

end
```

Here I could then check with which seed the model converges the fastest and then take that seed to run the model again with the chosen seed but with a tolerance of 1e-5?

```
min_log_length = argmin(log_length) 

best_seed = seeds[min_log_length]

Random.seed!(best_seed)

model = MMCTM([6, 7], [0.1, 0.1], X)
model_fit = fit!(model, tol=1e-5)

```
When I do this I get signatures that are similar but still differ from the signatures in your paper. 

Any help would be greatly appreciated!
Kerstin

**Comment by funnell** [comment]
Hi @kerstinth,

Please forgive the late reply. Rather than collect the length of the log likelihood values, you would take the final log-likelihood values for each run, then use those to calculate the ranks of the runs (separately for each modality, e.g. SNVs, SVs). Then for each run take the mean of the ranks (i.e. mean(snv_rank, sv_rank)), then take the run with the best mean rank. This is just one way to do it! 

I've added a script to the repo with an example of how to do this, see this function here https://github.com/shahcompbio/MultiModalMuSig.jl/blob/a1a4978658abf2ffd07b57b67e7b38034262f2f8/scripts/run_mmctm.jl#L163

I hope that helps, and if you have more questions I'm happy to try and answer them.

**Comment by kerstinth** [comment]
Hi @funnell ,

Thank you very much for your help and the script - this has helped me a lot! 
I can get your script running and it is creating output, except for the proportions file because it throws the following error: 

> ERROR: LoadError: MethodError: no method matching DataFrame(::Array{Float64,2}, ::Symbol)
> Closest candidates are:
>   DataFrame(::AbstractArray{T,2} where T) at /Users/kerstin/.julia/packages/DataFrames/GtZ1l/src/dataframe/dataframe.jl:267
>   DataFrame(::AbstractArray{T,2} where T, !Matched::AbstractArray{Symbol,1}; makeunique) at /Users/kerstin/.julia/packages/DataFrames/GtZ1l/src/dataframe/dataframe.jl:267
>   DataFrame(::AbstractArray{T,2} where T, !Matched::AbstractArray{#s35,1} where #s35<:AbstractString; makeunique) at /Users/kerstin/.julia/packages/DataFrames/GtZ1l/src/dataframe/dataframe.jl:272
>   ...
> Stacktrace:
>  [1] propdf(::MMCTM, ::Array{Symbol,1}, ::Array{String,1}) at /Volumes/lab-swantonc/working/tholk/GEL/MultiModalMutSigs/code/run_mmctm_TF.jl:233
>  [2] writeprops(::String, ::MMCTM, ::Array{Symbol,1}, ::Array{String,1}) at /Volumes/lab-swantonc/working/tholk/GEL/MultiModalMutSigs/code/run_mmctm_TF.jl:244
>  [3] main() at /Volumes/lab-swantonc/working/tholk/GEL/MultiModalMutSigs/code/run_mmctm_TF.jl:290
>  [4] top-level scope at none:0
>  [5] include at ./boot.jl:326 [inlined]
>  [6] include_relative(::Module, ::String) at ./loading.jl:1038
>  [7] include(::Module, ::String) at ./sysimg.jl:29
>  [8] exec_options(::Base.JLOptions) at ./client.jl:267
>  [9] _start() at ./client.jl:436
> in expression starting at /Volumes/lab-swantonc/working/tholk/GEL/MultiModalMutSigs/code/run_mmctm_TF.jl:294

so I think there might be a problem with the DataFrame function?

The command I am using is this:

```
/Users/kerstin/Applications/Julia-1.1.app/Contents/Resources/julia/bin/julia \
/Volumes/lab-swantonc/working/tholk/GEL/MultiModalMutSigs/code/run_mmctm_TF.jl \
{/Volumes/proj-tracerx-lung/tctProjects/mcgranahanLab/tholk/apps/MultiModalMuSig.jl/data/brca-eu_snv_counts.tsv,/Volumes/proj-tracerx-lung/tctProjects/mcgranahanLab/tholk/apps/MultiModalMuSig.jl/data/brca-eu_sv_counts.tsv} \
-k {6,7} \
-m "SNV" "SV" \
--model /Volumes/lab-swantonc/working/tholk/GEL/MultiModalMutSigs/data/run_mmctm_TF/model.jdl \
--mean /Volumes/lab-swantonc/working/tholk/GEL/MultiModalMutSigs/data/run_mmctm_TF/guassian_mean.txt \
--cov /Volumes/lab-swantonc/working/tholk/GEL/MultiModalMutSigs/data/run_mmctm_TF/gaussian_covariance.tsv \
--cor /Volumes/lab-swantonc/working/tholk/GEL/MultiModalMutSigs/data/run_mmctm_TF/correlation_output.tsv \
--sigs /Volumes/lab-swantonc/working/tholk/GEL/MultiModalMutSigs/data/run_mmctm_TF/signatures.tsv \
--props /Volumes/lab-swantonc/working/tholk/GEL/MultiModalMutSigs/data/run_mmctm_TF/signature_proportions.tsv \
--restarts 2
```

Is there anything I should be doing differently?

**Comment by funnell** [comment]
I noticed that you are using Julia 1.1 (most recent is 1.7.1). I think this error is because that bit of code needs a more recent version of the DataFrames library, which probably needs a more recent Julia version. Could you try either modifying the code in that script (I think you can just take out the `:auto` parameter), or update to the latest version of Julia etc.?

**Comment by kerstinth** [comment]
Taking out the :auto parameter worked! Thanks so much for your help again!
