### ISSUE TITLE
SV count matrix input example

### ISSUE THREAD

**Issue by timchu90** [shahcompbio/MultiModalMuSig.jl#13]
Hi!,
Thanks for your work on this tool! Do you have any documentation on how the example input matrix was generated?
https://github.com/shahcompbio/MultiModalMuSig.jl/blob/master/data/brca-eu_sv_counts.tsv

**Comment by timchu90** [comment]
Thanks! It does a little, though I was more interested in how exactly the level of homology was calculated in order to replicate the input matrix for our set of data.

**Comment by funnell** [comment]
No problem! Those values were output by the SV calling tool that we used: https://github.com/amcpherson/destruct

**Comment by timchu90** [comment]
Thank you!
