### ISSUE TITLE
Handling of Translocations in Independent-Feature Models

### ISSUE THREAD

**Issue by grasskind** [shahcompbio/MultiModalMuSig.jl#14]
Hi,

I was curious about how your independent-feature models handle events that don't have the full set of features. For example, if you include breakpoint distance as a feature, how do the models handle translocations? 

Thank you for your time!

**Comment by funnell** [comment]
Hello,

This is a good question! The independent feature models here don't account for missing features (e.g. breakpoint distance for translocations, as you've pointed out), which is an important limitation. When I was testing these models I set a unique breakpoint distance value for translocations only.

**Comment by grasskind** [comment]
I see, thank you!

**Comment by funnell** [comment]
No problem!
