### ISSUE TITLE
Cannot initiate MMCTM

### ISSUE THREAD

**Issue by WuyangFF95** [shahcompbio/MultiModalMuSig.jl#3]
Dear @funnell ,

I tried to begin running MMCTM or CTM on one of my dataset, but failed. 
The dataset is attached as:
[ground.truth.syn.catalog.tsv.zip](https://github.com/shahcompbio/MultiModalMuSig.jl/files/3292889/ground.truth.syn.catalog.tsv.zip)

It has of 96 Single-Base-Substitution mutations, and I think that there is only one modality (SBS) inside. Based on this assumption, I've written my code as follows:
`
using MultiModalMuSig
using CSV
using DataFrames
using VegaLite
using Random

## Specify seed used in the running
Random.seed!(1)

## Launching on the example dataset
snv_counts = CSV.read("ground.truth.syn.catalog.tsv", delim='\t')

**X = format_counts_mmctm(snv_counts)**
model = MMCTM([2], [0.1], X)
fit!(model, tol=1e-5)

snv_signatures = DataFrame(hcat(model.ϕ[1]...))
snv_signatures[:term] = snv_counts[:term]
snv_signatures = melt(
    snv_signatures, :term, variable_name=:signature, value_name=:probability
)
`

But it crashed on command which was highlighted bold. It said:

> ERROR: MethodError: no method matching format_counts_mmctm(::DataFrame)
> Closest candidates are:
>   format_counts_mmctm(::DataFrame, ::DataFrame) at /home/wuyang/.julia/dev/MultiModalMuSig/src/utils.jl:42
> Stacktrace:
>  [1] top-level scope at none:0

I tried another command, which was format_counts_ctm(snv_counts), and I got another error again:

> ERROR: UndefVarError: makecountmat not defined
> Stacktrace:
>  [1] format_counts_ctm(::DataFrame) at /home/wuyang/.julia/dev/MultiModalMuSig/src/utils.jl:32
>  [2] top-level scope at none:0

I went to **utils.jl** and tried to run the code in the format_counts_ctm() line by line, and it was stuck on utils.jl:36: ** for lib in names(countsdfs[1]) **

> ERROR: MethodError: no method matching names(::Array{Union{Missing, String},1})
> Closest candidates are:
>   names(::DataFrames.Index) at /home/wuyang/.julia/packages/DataFrames/IKMvt/src/other/index.jl:20
>   names(::Module; all, imported) at reflection.jl:98
>   names(::DataFrames.SubIndex) at /home/wuyang/.julia/packages/DataFrames/IKMvt/src/other/index.jl:317
>   ...
> Stacktrace:
>  [1] top-level scope at none:0

**Comment by WuyangFF95** [comment]
I was using Julia 1.1.0. I thought that maybe this version of Julia has reshaped the behavior or names(). Very interestingly, when I tried to refer to `names(countsdfs[1])`, It came out an error as follows:

> ERROR: MethodError: no method matching names(::Array{Union{Missing, String},1})
> Closest candidates are:
>   names(::DataFrames.Index) at /home/wuyang/.julia/packages/DataFrames/IKMvt/src/other/index.jl:20 
>   names(::Module; all, imported) at reflection.jl:98
>   names(::DataFrames.SubIndex) at /home/wuyang/.julia/packages/DataFrames/IKMvt/src/other/index.jl:317
>   ...
> Stacktrace:
>  [1] top-level scope at none:0

But if I tried to access the `names(countsdfs)[1]` instead, it will return a value without error:
> :term

I guess that is the purpose of writing utils:36. You basically tried to test whether the first column name of the data frame equals to :term. If not, the program would abort. But the tricky part is it aborted even if the first column name was :term.

**Comment by funnell** [comment]
Hi @WuyangFF95, can you check that you have the latest code? Try pulling master... I've also registered the package with the julia package repo, so you can install the latest version using the usual method as well if you prefer.

**Comment by funnell** [comment]
@WuyangFF95, did updating the package solve your issue?

**Comment by WuyangFF95** [comment]
Thank you @funnell !

Previously I was using a pre-release version (v0.0.0). Yesterday I upgraded to the latest version (v0.1.0) in Julia registry, and the issue has been solved.
