### ISSUE TITLE
How does MultiModalMuSig Infer Mutational Signatures and Signature Exposures?

### ISSUE THREAD

**Issue by WuyangFF95** [shahcompbio/MultiModalMuSig.jl#5]
Dear @funnell,

MultiModalMuSig.jl package uses a very ingenious generative model to design the dependency among all latent variables. But I'm curious about the strategy to estimate the latent variables and the mutational signatures and exposures. Do you use Expectation Maximization (EM), Markov Chain Monte Carlo (MCMC), Simulated Annealing (SA), or other strategies?

Thanks much!
Yang

**Comment by funnell** [comment]
Hi Yang,

I’m using variational inference for all the models in this package. 

Cheers!

**Comment by WuyangFF95** [comment]
Thank you Tyler!

Actually, I found in your paper that you are using EM algorithm for Variational Inference.

> For LDA and ILDA, parameters were inferred using mean-field Variational Bayes. For CTM,
> MMCTM, ICTM and IMMCTM, parameter inference was performed using mean-field variational EM. The MMCTM updates and derivations can be found in Salomatin et al. [22]. See S1
> Text for detailed descriptions of the topic models.

**Comment by funnell** [comment]
By the way @WuyangFF95, if you post a preprint of your work, I'd be interested to see the results of your comparisons!

**Comment by WuyangFF95** [comment]
Sure! I'll send the link to you once it's on a preprint archive.
